name: 'actions2slack'
description: 'Send to slack'
inputs:
  slack-channel:  # id of input
    description: 'Slack channel'
    required: true
    default: 'bottest'

  slack-token:  # id of input
    description: 'A slack token'
    required: true

  status:
    description: 'STARTED, SUCCEEDED, FAILED'
    required: true

  github-run-id:
    description: 'Github run id'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
